# fly.toml app configuration file generated for fiveevry on 2023-07-22T02:40:48+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

#app = "foot4ever"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
